version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cratedrop-backend
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV:-production}
      GIN_MODE: ${GIN_MODE:-release}
      BASE_URL: ${BASE_URL:-http://localhost}
      DATA_DIR: /data
      SQLITE_PATH: /data/db/cratedrop.sqlite
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret}
      REFRESH_SECRET: ${REFRESH_SECRET:-dev-refresh-secret}
    user: "1000:1000"
    volumes:
      - /mnt/music/cratedrop:/data:rw
      - ./logs:/app/logs:rw
    ports:
      - "8080:8080" # direct access (optional); nginx proxies to this
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthz"]
      interval: 30s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    container_name: cratedrop-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

# Postgres (optional, future). If you decide to switch from SQLite, enable below.
#  db:
#    image: postgres:16-bookworm  # arm64 compatible
#    container_name: music-postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: music_server
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - /mnt/music/postgres_data:/var/lib/postgresql/data
