version: '3.8'

services:
  db:
    image: postgres:16-bookworm  # arm64 compatible
    container_name: music-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: music_server
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Pulled from .env
    ports:
      - "5432:5432"
    volumes:
      - /mnt/music/postgres_data:/var/lib/postgresql/data  # Will bind to Pi's mount; local dev can use ./postgres_data
